name: flutter_notification
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  # path: ^1.8.0
  open_file_safe: ^3.2.3
  flutter_local_notifications: ^12.0.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  
  
